apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.gateway.app }}
  name: {{ .Values.gateway.service.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.gateway.service.port }}
    protocol: TCP
    targetPort: {{ .Values.gateway.service.targetPort }}
  selector:
    app: {{ .Values.gateway.app }}
  type: NodePort
