apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  nodeSelector:
    kubernetes.io/hostname: jts-1
  containers:
  - name: tf
    image: nvcr.io/nvidia/l4t-tensorflow:r32.4.3-tf2.2-py3
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
